os: osx
language: swift
osx_image: xcode11.6
script: 'xcodebuild clean test -project CI_Experiment.xcodeproj -scheme "CI_Experiment" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.6,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO'
notifications:
  email:
    recipients:
      - codergogoi@gmail.com
      - gogoi8419@gmail.com
    on_success: always
    on_failure: always

